# -*- coding: utf-8 -*-
"""Employee Burnout and Turnover Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mtIQRZ82FoNbT01t6zvCt5BMRqShZbDB
"""

from __future__ import annotations

import warnings

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    mean_squared_error,
    r2_score,
    roc_auc_score,
    roc_curve,
)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


# ============================================================================
# KONFIGURASI
# ============================================================================

DATA_FILE = "hr_data.csv"
RANDOM_STATE = 42

warnings.filterwarnings("ignore")

sns.set_theme(
    style="whitegrid",
    context="notebook",
)


# ============================================================================
# FUNGSI BANTUAN
# ============================================================================

def print_separator(title: str) -> None:
    """Menampilkan judul bagian dengan format yang konsisten."""
    print("\n" + "=" * 100)
    print(title)
    print("=" * 100)


def validate_required_columns(
    data: pd.DataFrame,
    required_columns: list[str],
) -> None:
    """Memastikan kolom penting tersedia di dataset."""
    missing_columns = [
        column for column in required_columns
        if column not in data.columns
    ]

    if missing_columns:
        raise ValueError(
            "Kolom berikut tidak ditemukan dalam dataset: "
            f"{missing_columns}"
        )


def convert_binary_columns(data: pd.DataFrame) -> pd.DataFrame:
    """
    Mengubah kolom biner penting menjadi format numerik.

    Attrition:
        No  -> 0
        Yes -> 1

    OverTime:
        No  -> 0
        Yes -> 1
    """
    result = data.copy()

    if result["Attrition"].dtype == "object":
        result["Attrition"] = (
            result["Attrition"]
            .astype(str)
            .str.strip()
            .str.lower()
            .map({
                "no": 0,
                "yes": 1,
            })
        )

    if result["OverTime"].dtype == "object":
        result["OverTime_Encoded"] = (
            result["OverTime"]
            .astype(str)
            .str.strip()
            .str.lower()
            .map({
                "no": 0,
                "yes": 1,
            })
        )
    else:
        result["OverTime_Encoded"] = pd.to_numeric(
            result["OverTime"],
            errors="coerce",
        )

    if result["Attrition"].isna().any():
        raise ValueError(
            "Kolom Attrition memiliki nilai selain No atau Yes."
        )

    if result["OverTime_Encoded"].isna().any():
        raise ValueError(
            "Kolom OverTime memiliki nilai yang tidak dikenali."
        )

    return result


def create_burnout_score(data: pd.DataFrame) -> pd.DataFrame:
    """
    Membuat Burnout Score simulasi pada rentang 0 sampai 1.

    Skor dibentuk berdasarkan:
    - Overtime
    - Work-life balance
    - Job satisfaction
    - Jumlah perusahaan sebelumnya
    - Masa kerja di perusahaan saat ini
    """
    result = data.copy()

    np.random.seed(RANDOM_STATE)

    overtime_component = (
        result["OverTime_Encoded"] * 0.35
    )

    work_life_component = (
        (4 - pd.to_numeric(result["WorkLifeBalance"], errors="coerce"))
        * 0.20
    )

    satisfaction_component = (
        (4 - pd.to_numeric(result["JobSatisfaction"], errors="coerce"))
        * 0.15
    )

    company_change_component = (
        pd.to_numeric(
            result["NumCompaniesWorked"],
            errors="coerce",
        )
        / 15
        * 0.10
    )

    short_tenure_component = (
        (
            pd.to_numeric(
                result["YearsAtCompany"],
                errors="coerce",
            )
            < 2
        ).astype(int)
        * 0.10
    )

    random_noise = np.random.normal(
        loc=0,
        scale=0.05,
        size=len(result),
    )

    result["BurnoutScore"] = (
        overtime_component
        + work_life_component
        + satisfaction_component
        + company_change_component
        + short_tenure_component
        + random_noise
    ).clip(0, 1)

    return result


# ============================================================================
# 1. RINGKASAN DATA
# ============================================================================

def display_summary(data: pd.DataFrame) -> None:
    """Menampilkan ringkasan umum dataset."""
    print_separator("PROJECT: EMPLOYEE BURNOUT AND TURNOVER ANALYSIS")

    print(f"Jumlah karyawan              : {len(data):,}")
    print(
        "Jumlah karyawan resign      : "
        f"{int(data['Attrition'].sum()):,}"
    )
    print(
        "Persentase attrition        : "
        f"{data['Attrition'].mean() * 100:.2f}%"
    )
    print(
        "Rata-rata Burnout Score     : "
        f"{data['BurnoutScore'].mean():.3f}"
    )
    print(
        "Burnout Score tertinggi     : "
        f"{data['BurnoutScore'].max():.3f}"
    )
    print(
        "Burnout Score terendah      : "
        f"{data['BurnoutScore'].min():.3f}"
    )


# ============================================================================
# 2. EXPLORATORY DATA ANALYSIS
# ============================================================================

def exploratory_data_analysis(data: pd.DataFrame) -> None:
    """Menampilkan dashboard eksplorasi data."""
    figure, axes = plt.subplots(
        nrows=2,
        ncols=3,
        figsize=(19, 11),
    )

    figure.suptitle(
        "EMPLOYEE BURNOUT AND TURNOVER ANALYSIS",
        fontsize=17,
        fontweight="bold",
    )

    # ------------------------------------------------------------------------
    # Distribusi Burnout Score
    # ------------------------------------------------------------------------
    sns.histplot(
        data=data,
        x="BurnoutScore",
        kde=True,
        bins=30,
        color="#E74C3C",
        ax=axes[0, 0],
    )

    mean_burnout = data["BurnoutScore"].mean()
    burnout_q75 = data["BurnoutScore"].quantile(0.75)

    axes[0, 0].axvline(
        mean_burnout,
        color="#2C3E50",
        linestyle="--",
        linewidth=2,
        label=f"Rata-rata: {mean_burnout:.2f}",
    )

    axes[0, 0].axvline(
        burnout_q75,
        color="#F39C12",
        linestyle="--",
        linewidth=2,
        label=f"Kuartil 75%: {burnout_q75:.2f}",
    )

    axes[0, 0].set_title(
        "Distribusi Burnout Score",
        fontweight="bold",
    )
    axes[0, 0].set_xlabel("Burnout Score")
    axes[0, 0].set_ylabel("Frekuensi")
    axes[0, 0].legend()

    # ------------------------------------------------------------------------
    # Burnout Score berdasarkan Attrition
    # ------------------------------------------------------------------------
    burnout_attrition = data.copy()
    burnout_attrition["Status"] = burnout_attrition["Attrition"].map(
        {
            0: "Tetap",
            1: "Resign",
        }
    )

    sns.boxplot(
        data=burnout_attrition,
        x="Status",
        y="BurnoutScore",
        order=["Tetap", "Resign"],
        palette={
            "Tetap": "#2ECC71",
            "Resign": "#E74C3C",
        },
        ax=axes[0, 1],
    )

    axes[0, 1].set_title(
        "Burnout Score berdasarkan Status Karyawan",
        fontweight="bold",
    )
    axes[0, 1].set_xlabel("Status Karyawan")
    axes[0, 1].set_ylabel("Burnout Score")

    # ------------------------------------------------------------------------
    # Burnout berdasarkan Department
    # ------------------------------------------------------------------------
    department_order = (
        data.groupby("Department")["BurnoutScore"]
        .median()
        .sort_values(ascending=False)
        .index
    )

    sns.boxplot(
        data=data,
        x="BurnoutScore",
        y="Department",
        order=department_order,
        palette="Reds_r",
        ax=axes[0, 2],
    )

    axes[0, 2].set_title(
        "Burnout Score berdasarkan Department",
        fontweight="bold",
    )
    axes[0, 2].set_xlabel("Burnout Score")
    axes[0, 2].set_ylabel("Department")

    # ------------------------------------------------------------------------
    # Burnout berdasarkan Overtime
    # ------------------------------------------------------------------------
    sns.boxplot(
        data=data,
        x="OverTime",
        y="BurnoutScore",
        order=["No", "Yes"],
        palette={
            "No": "#3498DB",
            "Yes": "#E74C3C",
        },
        ax=axes[1, 0],
    )

    axes[1, 0].set_title(
        "Burnout Score berdasarkan Overtime",
        fontweight="bold",
    )
    axes[1, 0].set_xlabel("Overtime")
    axes[1, 0].set_ylabel("Burnout Score")

    # ------------------------------------------------------------------------
    # Burnout berdasarkan Masa Kerja
    # ------------------------------------------------------------------------
    tenure_bins = [0, 2, 5, 10, 20, 100]
    tenure_labels = [
        "< 2 tahun",
        "2–5 tahun",
        "5–10 tahun",
        "10–20 tahun",
        "> 20 tahun",
    ]

    tenure_data = data.copy()
    tenure_data["TenureGroup"] = pd.cut(
        tenure_data["YearsAtCompany"],
        bins=tenure_bins,
        labels=tenure_labels,
        right=False,
    )

    sns.boxplot(
        data=tenure_data,
        x="TenureGroup",
        y="BurnoutScore",
        order=tenure_labels,
        palette="Blues_d",
        ax=axes[1, 1],
    )

    axes[1, 1].set_title(
        "Burnout Score berdasarkan Masa Kerja",
        fontweight="bold",
    )
    axes[1, 1].set_xlabel("Masa Kerja")
    axes[1, 1].set_ylabel("Burnout Score")
    axes[1, 1].tick_params(
        axis="x",
        rotation=30,
    )

    # ------------------------------------------------------------------------
    # Attrition Rate berdasarkan Department
    # ------------------------------------------------------------------------
    attrition_by_department = (
        data.groupby("Department")["Attrition"]
        .mean()
        .sort_values(ascending=False)
        * 100
    )

    department_colors = [
        "#E74C3C" if value > data["Attrition"].mean() * 100
        else "#2ECC71"
        for value in attrition_by_department.values
    ]

    axes[1, 2].bar(
        attrition_by_department.index,
        attrition_by_department.values,
        color=department_colors,
    )

    axes[1, 2].axhline(
        data["Attrition"].mean() * 100,
        color="#2C3E50",
        linestyle="--",
        linewidth=2,
        label=(
            f"Rata-rata keseluruhan: "
            f"{data['Attrition'].mean() * 100:.1f}%"
        ),
    )

    axes[1, 2].set_title(
        "Attrition Rate berdasarkan Department",
        fontweight="bold",
    )
    axes[1, 2].set_xlabel("Department")
    axes[1, 2].set_ylabel("Attrition Rate (%)")
    axes[1, 2].tick_params(
        axis="x",
        rotation=35,
    )
    axes[1, 2].legend()

    plt.tight_layout()
    plt.show()


# ============================================================================
# 3. ANALISIS KORELASI DAN HEATMAP
# ============================================================================

def correlation_analysis(data: pd.DataFrame) -> None:
    """
    Menampilkan heatmap korelasi yang telah diperbaiki.

    Kolom ID dan kolom konstan dikeluarkan karena tidak memiliki
    nilai analitis yang berguna.
    """
    excluded_columns = [
        "EmployeeNumber",
        "EmployeeCount",
        "StandardHours",
    ]

    correlation_data = data.copy()

    # Tambahkan variabel biner Overtime agar dapat dianalisis
    if "OverTime_Encoded" not in correlation_data.columns:
        correlation_data["OverTime_Encoded"] = (
            correlation_data["OverTime"]
            .astype(str)
            .str.strip()
            .str.lower()
            .map({
                "no": 0,
                "yes": 1,
            })
        )

    numeric_columns = correlation_data.select_dtypes(
        include=["number"]
    ).columns.tolist()

    numeric_columns = [
        column
        for column in numeric_columns
        if column not in excluded_columns
        and correlation_data[column].nunique(dropna=True) > 1
        and correlation_data[column].notna().sum() > 0
    ]

    correlation_matrix = correlation_data[numeric_columns].corr(
        method="pearson"
    )

    # ------------------------------------------------------------------------
    # Heatmap lengkap
    # ------------------------------------------------------------------------
    plt.figure(figsize=(18, 14))

    sns.heatmap(
        correlation_matrix,
        annot=True,
        fmt=".2f",
        cmap="RdBu_r",
        center=0,
        vmin=-1,
        vmax=1,
        linewidths=0.5,
        linecolor="white",
        square=True,
        cbar_kws={
            "label": "Koefisien Korelasi Pearson",
            "shrink": 0.8,
        },
    )

    plt.title(
        "HEATMAP KORELASI VARIABEL NUMERIK",
        fontsize=16,
        fontweight="bold",
        pad=20,
    )
    plt.xticks(
        rotation=45,
        ha="right",
    )
    plt.yticks(rotation=0)
    plt.tight_layout()
    plt.show()

    print_separator("MATRIKS KORELASI LENGKAP")
    print(correlation_matrix.round(3).to_string())

    # ------------------------------------------------------------------------
    # Daftar pasangan korelasi terkuat
    # ------------------------------------------------------------------------
    upper_triangle = correlation_matrix.where(
        np.triu(
            np.ones(correlation_matrix.shape),
            k=1,
        ).astype(bool)
    )

    correlation_pairs = (
        upper_triangle
        .stack()
        .reset_index()
    )

    correlation_pairs.columns = [
        "Variabel 1",
        "Variabel 2",
        "Korelasi",
    ]

    correlation_pairs["Korelasi Absolut"] = (
        correlation_pairs["Korelasi"].abs()
    )

    correlation_pairs = (
        correlation_pairs
        .sort_values(
            "Korelasi Absolut",
            ascending=False,
        )
        .drop(columns=["Korelasi Absolut"])
        .reset_index(drop=True)
    )

    print_separator("10 PASANGAN VARIABEL DENGAN KORELASI TERKUAT")
    print(
        correlation_pairs
        .head(10)
        .round(3)
        .to_string(index=False)
    )

    # ------------------------------------------------------------------------
    # Heatmap tanpa BurnoutScore untuk mengurangi risiko interpretasi bias
    # ------------------------------------------------------------------------
    correlation_without_burnout = correlation_matrix.drop(
        index=["BurnoutScore"],
        columns=["BurnoutScore"],
        errors="ignore",
    )

    plt.figure(figsize=(18, 14))

    sns.heatmap(
        correlation_without_burnout,
        annot=True,
        fmt=".2f",
        cmap="RdBu_r",
        center=0,
        vmin=-1,
        vmax=1,
        linewidths=0.5,
        linecolor="white",
        square=True,
        cbar_kws={
            "label": "Koefisien Korelasi Pearson",
            "shrink": 0.8,
        },
    )

    plt.title(
        "HEATMAP KORELASI TANPA BURNOUT SCORE",
        fontsize=16,
        fontweight="bold",
        pad=20,
    )
    plt.xticks(
        rotation=45,
        ha="right",
    )
    plt.yticks(rotation=0)
    plt.tight_layout()
    plt.show()


# ============================================================================
# 4. PREPROCESSING
# ============================================================================

def prepare_model_data(
    data: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Menyiapkan data untuk machine learning.

    Menghasilkan:
    - Data yang sudah diencoding
    - Data yang sudah distandardisasi
    """
    model_data = data.copy()

    categorical_columns = model_data.select_dtypes(
        include=["object", "category"]
    ).columns

    for column in categorical_columns:
        model_data[column] = (
            model_data[column]
            .astype("category")
            .cat.codes
        )

    model_data = model_data.drop(
        columns=[
            "EmployeeCount",
            "Over18",
            "StandardHours",
            "EmployeeNumber",
            "TenureGroup",
            "OverTime",
        ],
        errors="ignore",
    )

    model_data = model_data.apply(
        pd.to_numeric,
        errors="coerce",
    )

    model_data = model_data.fillna(
        model_data.median(numeric_only=True)
    )

    scaled_data = model_data.copy()

    feature_columns = [
        column
        for column in scaled_data.select_dtypes(
            include=["number"]
        ).columns
        if column not in [
            "Attrition",
            "BurnoutScore",
        ]
    ]

    scaler = StandardScaler()
    scaled_data[feature_columns] = scaler.fit_transform(
        scaled_data[feature_columns]
    )

    return model_data, scaled_data


# ============================================================================
# 5. REGRESI BURNOUT SCORE
# ============================================================================

def burnout_regression(
    model_data: pd.DataFrame,
) -> None:
    """Memprediksi Burnout Score menggunakan Random Forest Regressor."""
    features = model_data.drop(
        columns=[
            "BurnoutScore",
            "Attrition",
        ],
        errors="ignore",
    )

    target = model_data["BurnoutScore"]

    x_train, x_test, y_train, y_test = train_test_split(
        features,
        target,
        test_size=0.20,
        random_state=RANDOM_STATE,
    )

    model = RandomForestRegressor(
        n_estimators=200,
        max_depth=10,
        random_state=RANDOM_STATE,
        n_jobs=-1,
    )

    model.fit(x_train, y_train)

    predictions = model.predict(x_test)

    r2 = r2_score(y_test, predictions)
    mse = mean_squared_error(y_test, predictions)
    rmse = np.sqrt(mse)

    print_separator("REGRESI BURNOUT SCORE")
    print(f"R² Score : {r2:.4f}")
    print(f"MSE      : {mse:.4f}")
    print(f"RMSE     : {rmse:.4f}")

    feature_importance = (
        pd.DataFrame(
            {
                "Feature": features.columns,
                "Importance": model.feature_importances_,
            }
        )
        .sort_values(
            "Importance",
            ascending=False,
        )
        .reset_index(drop=True)
    )

    print_separator("10 FITUR TERPENTING UNTUK PREDIKSI BURNOUT")
    print(
        feature_importance
        .head(10)
        .round(4)
        .to_string(index=False)
    )

    top_features = feature_importance.head(10)

    plt.figure(figsize=(10, 7))

    plt.barh(
        top_features["Feature"][::-1],
        top_features["Importance"][::-1],
        color="#E74C3C",
    )

    plt.title(
        "10 Fitur Terpenting untuk Prediksi Burnout",
        fontweight="bold",
    )
    plt.xlabel("Importance Score")
    plt.ylabel("Feature")
    plt.tight_layout()
    plt.show()


# ============================================================================
# 6. KLASIFIKASI ATTRITION
# ============================================================================

def attrition_classification(
    model_data: pd.DataFrame,
) -> None:
    """Memprediksi Attrition menggunakan Random Forest Classifier."""
    features = model_data.drop(
        columns=["Attrition"],
        errors="ignore",
    )

    target = model_data["Attrition"].astype(int)

    x_train, x_test, y_train, y_test = train_test_split(
        features,
        target,
        test_size=0.20,
        random_state=RANDOM_STATE,
        stratify=target,
    )

    model = RandomForestClassifier(
        n_estimators=200,
        max_depth=10,
        random_state=RANDOM_STATE,
        n_jobs=-1,
        class_weight="balanced",
    )

    model.fit(x_train, y_train)

    predictions = model.predict(x_test)
    probabilities = model.predict_proba(x_test)[:, 1]

    roc_auc = roc_auc_score(
        y_test,
        probabilities,
    )

    matrix = confusion_matrix(
        y_test,
        predictions,
        labels=[0, 1],
    )

    print_separator("KLASIFIKASI TURNOVER / ATTRITION")
    print(f"ROC-AUC Score : {roc_auc:.4f}")

    print("\nClassification Report:")
    print(
        classification_report(
            y_test,
            predictions,
            labels=[0, 1],
            target_names=["Tetap", "Resign"],
            zero_division=0,
        )
    )

    # ------------------------------------------------------------------------
    # Confusion Matrix dan ROC Curve
    # ------------------------------------------------------------------------
    figure, axes = plt.subplots(
        nrows=1,
        ncols=2,
        figsize=(14, 5),
    )

    sns.heatmap(
        matrix,
        annot=True,
        fmt="d",
        cmap="Blues",
        xticklabels=["Tetap", "Resign"],
        yticklabels=["Tetap", "Resign"],
        ax=axes[0],
    )

    axes[0].set_title(
        "Confusion Matrix",
        fontweight="bold",
    )
    axes[0].set_xlabel("Prediksi Model")
    axes[0].set_ylabel("Kondisi Aktual")

    false_positive_rate, true_positive_rate, _ = roc_curve(
        y_test,
        probabilities,
    )

    axes[1].plot(
        false_positive_rate,
        true_positive_rate,
        color="#E74C3C",
        linewidth=2,
        label=f"ROC-AUC = {roc_auc:.4f}",
    )

    axes[1].plot(
        [0, 1],
        [0, 1],
        color="#2C3E50",
        linestyle="--",
        linewidth=1,
    )

    axes[1].set_title(
        "ROC Curve",
        fontweight="bold",
    )
    axes[1].set_xlabel("False Positive Rate")
    axes[1].set_ylabel("True Positive Rate")
    axes[1].legend()

    plt.tight_layout()
    plt.show()


# ============================================================================
# 7. CLUSTERING KARYAWAN
# ============================================================================

def employee_clustering(
    original_data: pd.DataFrame,
    scaled_data: pd.DataFrame,
) -> pd.DataFrame:
    """
    Mengelompokkan karyawan menggunakan K-Means.

    Proses clustering menggunakan data terstandardisasi.
    Profil cluster dihitung menggunakan data asli.
    """
    cluster_features = [
        "BurnoutScore",
        "JobSatisfaction",
        "WorkLifeBalance",
        "YearsAtCompany",
        "NumCompaniesWorked",
        "OverTime_Encoded",
    ]

    missing_features = [
        column
        for column in cluster_features
        if column not in scaled_data.columns
    ]

    if missing_features:
        raise ValueError(
            "Fitur clustering tidak ditemukan: "
            f"{missing_features}"
        )

    cluster_input = scaled_data[cluster_features].copy()

    # ------------------------------------------------------------------------
    # Elbow Method
    # ------------------------------------------------------------------------
    inertia_values = []
    cluster_range = range(2, 10)

    for number_of_clusters in cluster_range:
        temporary_model = KMeans(
            n_clusters=number_of_clusters,
            random_state=RANDOM_STATE,
            n_init=10,
        )

        temporary_model.fit(cluster_input)
        inertia_values.append(temporary_model.inertia_)

    plt.figure(figsize=(9, 5))

    plt.plot(
        list(cluster_range),
        inertia_values,
        marker="o",
        color="#E74C3C",
        linewidth=2,
    )

    plt.axvline(
        x=3,
        color="#2C3E50",
        linestyle="--",
        linewidth=2,
        label="Jumlah cluster yang digunakan: 3",
    )

    plt.title(
        "Elbow Method untuk Menentukan Jumlah Cluster",
        fontweight="bold",
    )
    plt.xlabel("Jumlah Cluster")
    plt.ylabel("Inertia")
    plt.legend()
    plt.tight_layout()
    plt.show()

    # ------------------------------------------------------------------------
    # K-Means dengan 3 cluster
    # ------------------------------------------------------------------------
    clustering_model = KMeans(
        n_clusters=3,
        random_state=RANDOM_STATE,
        n_init=10,
    )

    cluster_labels = clustering_model.fit_predict(
        cluster_input
    )

    clustered_data = original_data.copy()
    clustered_data["Cluster"] = cluster_labels

    # ------------------------------------------------------------------------
    # PCA Visualization
    # ------------------------------------------------------------------------
    pca = PCA(
        n_components=2,
        random_state=RANDOM_STATE,
    )

    pca_result = pca.fit_transform(cluster_input)

    clustered_data["PCA1"] = pca_result[:, 0]
    clustered_data["PCA2"] = pca_result[:, 1]

    # ------------------------------------------------------------------------
    # Profil cluster menggunakan nilai asli
    # ------------------------------------------------------------------------
    cluster_profile = (
        clustered_data
        .groupby("Cluster")
        [
            [
                "BurnoutScore",
                "JobSatisfaction",
                "WorkLifeBalance",
                "YearsAtCompany",
                "NumCompaniesWorked",
                "Attrition",
            ]
        ]
        .mean()
    )

    cluster_profile["Size"] = (
        clustered_data
        .groupby("Cluster")
        .size()
    )

    cluster_profile["AttritionRate"] = (
        clustered_data
        .groupby("Cluster")["Attrition"]
        .mean()
        * 100
    )

    print_separator("PROFIL KARYAWAN BERDASARKAN CLUSTER")

    print(
        cluster_profile
        .round(3)
        .to_string()
    )

    # ------------------------------------------------------------------------
    # Visualisasi cluster
    # ------------------------------------------------------------------------
    figure, axes = plt.subplots(
        nrows=1,
        ncols=2,
        figsize=(16, 6),
    )

    scatter = axes[0].scatter(
        clustered_data["PCA1"],
        clustered_data["PCA2"],
        c=clustered_data["Cluster"],
        cmap="viridis",
        alpha=0.70,
        s=55,
    )

    axes[0].set_title(
        "Visualisasi Cluster menggunakan PCA",
        fontweight="bold",
    )
    axes[0].set_xlabel("PCA Component 1")
    axes[0].set_ylabel("PCA Component 2")

    figure.colorbar(
        scatter,
        ax=axes[0],
        label="Cluster",
    )

    # Tabel ringkasan cluster
    table_data = cluster_profile[
        [
            "BurnoutScore",
            "JobSatisfaction",
            "WorkLifeBalance",
            "YearsAtCompany",
            "AttritionRate",
            "Size",
        ]
    ].round(2)

    table_data.columns = [
        "Burnout",
        "Job Sat.",
        "Work-Life",
        "Tenure",
        "Attrition (%)",
        "Jumlah",
    ]

    axes[1].axis("off")

    cluster_table = axes[1].table(
        cellText=table_data.values,
        rowLabels=[
            f"Cluster {index}"
            for index in table_data.index
        ],
        colLabels=table_data.columns,
        cellLoc="center",
        loc="center",
    )

    cluster_table.auto_set_font_size(False)
    cluster_table.set_fontsize(9)
    cluster_table.scale(1.2, 1.7)

    cluster_colors = [
        "#2ECC71",
        "#F39C12",
        "#E74C3C",
    ]

    for row_index in range(len(table_data)):
        for column_index in range(len(table_data.columns)):
            cluster_table[
                (row_index + 1, column_index)
            ].set_facecolor(
                cluster_colors[
                    row_index % len(cluster_colors)
                ]
            )

    plt.tight_layout()
    plt.show()

    return clustered_data


# ============================================================================
# 8. EARLY WARNING SYSTEM
# ============================================================================

def early_warning_system(
    data: pd.DataFrame,
) -> pd.DataFrame:
    """
    Mengelompokkan karyawan berdasarkan tingkat risiko turnover.

    Penting:
    Fungsi ini menggunakan data asli, bukan data yang sudah
    distandardisasi, agar threshold memiliki makna yang benar.
    """
    result = data.copy()

    burnout_threshold = result["BurnoutScore"].quantile(0.75)
    satisfaction_threshold = result["JobSatisfaction"].quantile(0.25)
    tenure_threshold = 2

    result["RiskLevel"] = "Low"

    medium_risk = (
        (result["BurnoutScore"] > burnout_threshold)
        & (
            result["JobSatisfaction"]
            < satisfaction_threshold
        )
    )

    high_risk = (
        (result["BurnoutScore"] > burnout_threshold)
        & (
            result["JobSatisfaction"]
            < satisfaction_threshold
        )
        & (
            result["YearsAtCompany"]
            < tenure_threshold
        )
    )

    result.loc[medium_risk, "RiskLevel"] = "Medium"
    result.loc[high_risk, "RiskLevel"] = "High"

    risk_order = [
        "Low",
        "Medium",
        "High",
    ]

    risk_distribution = (
        result["RiskLevel"]
        .value_counts()
        .reindex(
            risk_order,
            fill_value=0,
        )
    )

    attrition_by_risk = (
        result
        .groupby("RiskLevel")["Attrition"]
        .mean()
        .mul(100)
        .reindex(risk_order)
    )

    print_separator(
        "EARLY WARNING SYSTEM - RISIKO TURNOVER"
    )

    print(
        f"Burnout Score threshold 75%       : "
        f"{burnout_threshold:.3f}"
    )
    print(
        f"Job Satisfaction threshold 25%    : "
        f"{satisfaction_threshold:.3f}"
    )
    print(
        f"Threshold masa kerja              : "
        f"{tenure_threshold} tahun"
    )

    print("\nDistribusi Level Risiko:")
    print(risk_distribution.to_string())

    print("\nAttrition Rate berdasarkan Level Risiko:")
    print(attrition_by_risk.round(2).to_string())

    # ------------------------------------------------------------------------
    # Visualisasi Early Warning System
    # ------------------------------------------------------------------------
    figure, axes = plt.subplots(
        nrows=1,
        ncols=2,
        figsize=(14, 5),
    )

    risk_colors = {
        "Low": "#2ECC71",
        "Medium": "#F39C12",
        "High": "#E74C3C",
    }

    colors = [
        risk_colors[level]
        for level in risk_order
    ]

    bars = axes[0].bar(
        risk_distribution.index,
        risk_distribution.values,
        color=colors,
    )

    axes[0].set_title(
        "Distribusi Level Risiko",
        fontweight="bold",
    )
    axes[0].set_xlabel("Level Risiko")
    axes[0].set_ylabel("Jumlah Karyawan")

    for bar, value in zip(
        bars,
        risk_distribution.values,
    ):
        axes[0].text(
            bar.get_x() + bar.get_width() / 2,
            bar.get_height(),
            str(value),
            ha="center",
            va="bottom",
            fontweight="bold",
        )

    bars = axes[1].bar(
        attrition_by_risk.index,
        attrition_by_risk.values,
        color=colors,
    )

    axes[1].axhline(
        result["Attrition"].mean() * 100,
        color="#2C3E50",
        linestyle="--",
        linewidth=2,
        label=(
            f"Rata-rata keseluruhan: "
            f"{result['Attrition'].mean() * 100:.1f}%"
        ),
    )

    axes[1].set_title(
        "Attrition Rate berdasarkan Level Risiko",
        fontweight="bold",
    )
    axes[1].set_xlabel("Level Risiko")
    axes[1].set_ylabel("Attrition Rate (%)")
    axes[1].legend()

    for bar, value in zip(
        bars,
        attrition_by_risk.values,
    ):
        if not np.isnan(value):
            axes[1].text(
                bar.get_x() + bar.get_width() / 2,
                bar.get_height(),
                f"{value:.1f}%",
                ha="center",
                va="bottom",
                fontweight="bold",
            )

    plt.tight_layout()
    plt.show()

    return result


# ============================================================================
# 9. REKOMENDASI BISNIS
# ============================================================================

def display_business_recommendations(
    data: pd.DataFrame,
) -> None:
    """Menampilkan rekomendasi berdasarkan hasil analisis."""
    highest_attrition_department = (
        data.groupby("Department")["Attrition"]
        .mean()
        .mul(100)
        .sort_values(ascending=False)
        .index[0]
    )

    highest_attrition_rate = (
        data.groupby("Department")["Attrition"]
        .mean()
        .mul(100)
        .max()
    )

    highest_burnout_cluster = (
        data.groupby("Cluster")["BurnoutScore"]
        .mean()
        .idxmax()
    )

    high_risk_count = (
        data["RiskLevel"] == "High"
    ).sum()

    overtime_high_burnout_count = (
        (
            data["OverTime_Encoded"] == 1
        )
        & (
            data["BurnoutScore"]
            > data["BurnoutScore"].mean()
        )
    ).sum()

    print_separator("REKOMENDASI BISNIS")

    print(
        f"1. Prioritaskan Cluster {highest_burnout_cluster} "
        "untuk intervensi burnout."
    )
    print(
        "   Rekomendasi: mentoring, evaluasi beban kerja, "
        "dan fleksibilitas jam kerja."
    )

    print(
        f"\n2. Terdapat {high_risk_count:,} karyawan "
        "dalam kategori High Risk."
    )
    print(
        "   Rekomendasi: lakukan check-in rutin dengan HR, "
        "evaluasi kompensasi, dan berikan dukungan tambahan."
    )

    print(
        f"\n3. Department dengan attrition rate tertinggi adalah "
        f"{highest_attrition_department} "
        f"({highest_attrition_rate:.2f}%)."
    )
    print(
        "   Rekomendasi: lakukan analisis lanjutan terkait "
        "beban kerja, kepemimpinan, dan kepuasan karyawan."
    )

    print(
        f"\n4. Terdapat {overtime_high_burnout_count:,} karyawan "
        "yang mengalami overtime dan memiliki Burnout Score "
        "di atas rata-rata."
    )
    print(
        "   Rekomendasi: evaluasi kebutuhan rekrutmen, "
        "otomatisasi proses, dan pembagian beban kerja."
    )


# ============================================================================
# 10. PROGRAM UTAMA
# ============================================================================

def main() -> None:
    """Menjalankan seluruh proses analisis."""
    data = pd.read_csv(DATA_FILE)

    required_columns = [
        "Attrition",
        "OverTime",
        "WorkLifeBalance",
        "JobSatisfaction",
        "NumCompaniesWorked",
        "YearsAtCompany",
        "Department",
    ]

    validate_required_columns(
        data,
        required_columns,
    )

    data = convert_binary_columns(data)
    data = create_burnout_score(data)

    display_summary(data)
    exploratory_data_analysis(data)
    correlation_analysis(data)

    model_data, scaled_data = prepare_model_data(data)

    burnout_regression(model_data)
    attrition_classification(model_data)

    data_with_clusters = employee_clustering(
        original_data=data,
        scaled_data=scaled_data,
    )

    data_with_risk = early_warning_system(
        data_with_clusters,
    )

    display_business_recommendations(
        data_with_risk,
    )

if __name__ == "__main__":
    main()